# Generated by Django 4.2 on 2023-05-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_date',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure_date',
            new_name='departure_time',
        ),
    ]
